"""Independent human-style query bank for hck_GPT routing audits.

These prompts are deliberately kept outside ``vocabulary.py``. They include
filler words, slang, omitted diacritics, typos, mixed PL/EN and indirect
wording. Production phrases must not copy these prompts verbatim.
"""
from __future__ import annotations


# (group, query, accepted intents)
HUMAN_QUERY_CASES = [
    # Hardware and live readings
    ("hardware", "ej, jaki dokładnie procek siedzi w tej maszynie?", {"hw_cpu"}),
    ("hardware", "podaj pełną nazwę CPU, nie tylko jego użycie", {"hw_cpu"}),
    ("hardware", "co ja właściwie mam za procesor pod maską", {"hw_cpu"}),
    ("hardware", "could you identify the exact processor in this box?", {"hw_cpu"}),
    ("hardware", "pokaż nazwę grafiki i ile ma własnej pamięci", {"hw_gpu"}),
    ("hardware", "jaka karta odpowiada teraz za wyświetlanie obrazu?", {"hw_gpu"}),
    ("hardware", "which graphics adapter did Windows detect?", {"hw_gpu"}),
    ("hardware", "ile fizycznego ramu faktycznie widzi teraz system?", {"hw_ram"}),
    ("hardware", "mam jedną czy kilka kości pamięci operacyjnej?", {"hw_ram"}),
    ("hardware", "how much memory is installed, not currently free?", {"hw_ram"}),
    ("hardware", "co to za płyta główna, na której siedzą te części?", {"hw_motherboard"}),
    ("hardware", "can you read the board manufacturer and model?", {"hw_motherboard"}),
    ("hardware", "na którym nośniku zostało mi najmniej miejsca?", {"hw_storage"}),
    ("hardware", "rozpisz dyski, pojemności i wolne miejsce", {"hw_storage"}),
    ("hardware", "what storage devices are actually connected?", {"hw_storage"}),
    ("hardware", "streść mi wszystkie bebechy tego peceta", {"hw_all"}),
    ("hardware", "potrzebuję pełnego zestawienia sprzętu w jednym miejscu", {"hw_all"}),
    ("hardware", "give me the complete machine spec, component by component", {"hw_all"}),
    ("live", "czy coś się teraz gotuje w obudowie?", {"temperature", "hottest_component"}),
    ("live", "jak ciepły jest obecnie komputer pod obciążeniem?", {"temperature"}),
    ("live", "are the temperatures safe at this very moment?", {"temperature"}),
    ("live", "procek zbija taktowanie, bo zrobiło mu się za gorąco?", {"throttle_check"}),
    ("live", "czy widać dławienie termiczne przy tym obciążeniu?", {"throttle_check"}),
    ("live", "is heat forcing the CPU clocks down right now?", {"throttle_check"}),
    ("live", "która część jest w tej chwili najcieplejsza?", {"hottest_component"}),
    ("live", "wskaż największy odczyt temperatury w komputerze", {"hottest_component"}),
    ("live", "what is the hottest sensor you can see?", {"hottest_component"}),
    ("live", "daj surowe odczyty ze wszystkich dostępnych czujników", {"sensor_report"}),
    ("live", "which sensors are real and which readings are estimated?", {"sensor_report"}),
    ("live", "z jaką częstotliwością naprawdę pracuje teraz procesor?", {"cpu_clock"}),
    ("live", "show the current CPU frequency, not the advertised boost", {"cpu_clock"}),
    ("live", "ile pamięci karty jest obecnie zajęte?", {"vram_usage"}),
    ("live", "how much graphics memory is in use right now?", {"vram_usage"}),
    ("live", "czy linie napięcia wyglądają podejrzanie?", {"voltage_check"}),
    ("live", "does the voltage telemetry stay within a sane range?", {"voltage_check"}),
    ("live", "z jaką prędkością kręcą się obecnie wentylatory?", {"fan_speed"}),
    ("live", "can you read the fan RPM values?", {"fan_speed"}),
    ("live", "jak komputer radzi sobie wydajnościowo w tej chwili?", {"performance"}),
    ("live", "give me a quick live performance overview", {"performance"}),
    ("live", "pokaż liczby z obecnej sesji zamiast ogólnej opinii", {"stats"}),
    ("live", "how long has Windows been running without a reboot?", {"uptime"}),

    # Diagnosis, processes and Windows
    ("diagnosis", "od paru dni wszystko reaguje jakby z opóźnieniem", {"why_slow"}),
    ("diagnosis", "komp nagle dostał zadyszki, znajdź powód", {"why_slow"}),
    ("diagnosis", "why does the whole machine feel sluggish today?", {"why_slow"}),
    ("diagnosis", "co mogę bezpiecznie zrobić, żeby pecet odzyskał szybkość?", {"speed_up_pc"}),
    ("diagnosis", "give me a safe plan to make Windows less sluggish", {"speed_up_pc"}),
    ("diagnosis", "pamięć jest prawie pełna mimo że nic dużego nie odpalałem", {"ram_why_high"}),
    ("diagnosis", "gdzie zniknął cały RAM po kilku godzinach pracy?", {"ram_why_high"}),
    ("diagnosis", "why is memory usage so high with almost nothing open?", {"ram_why_high"}),
    ("diagnosis", "dysk świeci na sto procent, co go tak męczy?", {"disk_usage_why"}),
    ("diagnosis", "what keeps hammering the drive in the background?", {"disk_usage_why"}),
    ("diagnosis", "która aplikacja zabiera teraz najwięcej zasobów?", {"top_resource_hog"}),
    ("diagnosis", "wskaż jednego największego pożeracza CPU albo RAM", {"top_resource_hog"}),
    ("diagnosis", "show me the worst resource offender right now", {"top_resource_hog"}),
    ("diagnosis", "wylistuj programy działające obecnie w tle", {"processes"}),
    ("diagnosis", "what is running on the computer at the moment?", {"processes"}),
    ("diagnosis", "co robi ten cały RuntimeBroker.exe?", {"process_info", "process_identity"}),
    ("diagnosis", "tell me what SearchHost.exe is responsible for", {"process_info", "process_identity"}),
    ("diagnosis", "czy svchost.exe jest systemowy czy ktoś się pod niego podszywa?", {"process_identity", "virus_check"}),
    ("diagnosis", "identify audiodg.exe and tell me whether it belongs to Windows", {"process_identity"}),
    ("diagnosis", "czy mogę bezpiecznie zakończyć Discord.exe?", {"process_kill"}),
    ("diagnosis", "would closing OneDrive.exe from Task Manager be dangerous?", {"process_kill"}),
    ("diagnosis", "ten dziwny proces wygląda jak wirus, możesz to ocenić?", {"virus_check"}),
    ("diagnosis", "does this executable look suspicious or legitimate?", {"virus_check"}),
    ("diagnosis", "co startuje razem z Windowsem i wydłuża uruchamianie?", {"startup_check", "startup_slowdown"}),
    ("diagnosis", "show everything registered to launch at sign-in", {"startup_check"}),
    ("diagnosis", "czy Steam powinien automatycznie wstawać z systemem?", {"startup_safety"}),
    ("diagnosis", "is it sensible to disable Teams at startup?", {"startup_safety"}),
    ("diagnosis", "boot trwa coraz dłużej, co doszło do autostartu?", {"startup_slowdown"}),
    ("diagnosis", "Windows reaches the desktop much slower than before", {"startup_slowdown"}),
    ("diagnosis", "których zainstalowanych aplikacji prawie nigdy nie dotykam?", {"stale_apps"}),
    ("diagnosis", "find programs I have not used for a long time", {"stale_apps"}),
    ("diagnosis", "co z tych programów jest zbędne, ale nie usuwaj niczego", {"unnecessary_programs"}),
    ("diagnosis", "which background apps are probably unnecessary?", {"unnecessary_programs"}),
    ("diagnosis", "czy sterowniki urządzeń wyglądają na zaniedbane?", {"driver_status"}),
    ("diagnosis", "do any important drivers appear outdated?", {"driver_status"}),
    ("diagnosis", "obraz zamarł, lecz dźwięk przez chwilę dalej leciał", {"symptom_freeze", "crash_context"}),
    ("diagnosis", "the PC locks up for several seconds and then recovers", {"symptom_freeze"}),
    ("diagnosis", "wentylatory wyją nawet kiedy siedzę tylko na pulpicie", {"symptom_noisy"}),
    ("diagnosis", "why is the computer loud while basically idle?", {"symptom_noisy"}),
    ("diagnosis", "zniknęły ikony i pasek zadań, ale mysz nadal działa", {"desktop_problem"}),
    ("diagnosis", "mam czarny pulpit po zalogowaniu, co sprawdzić?", {"desktop_problem"}),
    ("diagnosis", "the taskbar and desktop stopped responding", {"desktop_problem"}),
    ("diagnosis", "co działo się ze sprzętem chwilę przed ostatnim zwisem?", {"crash_context"}),
    ("diagnosis", "reconstruct what happened just before the crash", {"crash_context"}),
    ("diagnosis", "przeglądarka puchnie po całym dniu i nie oddaje pamięci", {"browser_cache"}),
    ("diagnosis", "would browser tabs or cache explain this RAM use?", {"browser_cache"}),
    ("diagnosis", "czy system zaczął korzystać z pliku stronicowania?", {"swap_analysis"}),
    ("diagnosis", "is Windows paging because physical memory ran out?", {"swap_analysis"}),
    ("diagnosis", "kopiowanie na pendrive nagle zwolniło do zera", {"usb_transfer"}),
    ("diagnosis", "why does my USB transfer keep stalling?", {"usb_transfer"}),
    ("diagnosis", "jaki program wysyła teraz najwięcej danych przez sieć?", {"network_usage"}),
    ("diagnosis", "show which application is consuming the connection", {"network_usage"}),
    ("diagnosis", "czy dysk ma oznaki zużycia albo błędów?", {"disk_health"}),
    ("diagnosis", "does the drive health data suggest it may be failing?", {"disk_health"}),
    ("diagnosis", "zmierz, czy ten dysk jest faktycznie wolny", {"disk_speed"}),
    ("diagnosis", "how fast is the storage device in practice?", {"disk_speed"}),

    # History, comparison and proactivity
    ("history", "czy komputer działa gorzej niż w zeszłym tygodniu?", {"perf_change", "weekly_trends"}),
    ("history", "has performance measurably changed since last week?", {"perf_change"}),
    ("history", "porównaj zachowanie komputera do jego normalnego poziomu", {"compare_baseline"}),
    ("history", "is today's load unusual for this machine?", {"compare_baseline"}),
    ("history", "co konkretnie zmieniło się od wczoraj na tym PC?", {"pc_changes"}),
    ("history", "did anything important change on the computer today?", {"pc_changes"}),
    ("history", "zestaw obecną sesję z poprzednim uruchomieniem programu", {"session_compare"}),
    ("history", "compare this session against the previous one", {"session_compare"}),
    ("history", "podsumuj mi dzisiejszą pracę komputera w kilku punktach", {"session_digest"}),
    ("history", "give me a concise digest of this session", {"session_digest"}),
    ("history", "zrób poranny przegląd zanim zacznę pracę", {"morning_brief"}),
    ("history", "what should I know about the PC this morning?", {"morning_brief"}),
    ("history", "pokaż tendencje z ostatnich kilku tygodni", {"weekly_trends"}),
    ("history", "what has been trending up or down lately?", {"weekly_trends"}),
    ("history", "czy temperatury robią się wyższe z każdym tygodniem?", {"thermal_history", "temp_comparison"}),
    ("history", "show the long-term temperature history", {"thermal_history"}),
    ("history", "czy dzisiaj jest cieplej niż podczas poprzedniej sesji?", {"temp_comparison"}),
    ("history", "compare today's heat against the earlier reading", {"temp_comparison"}),
    ("history", "przewidujesz przegrzewanie, jeśli obciążenie się utrzyma?", {"thermal_prediction"}),
    ("history", "will the current temperature trend become unsafe soon?", {"thermal_prediction"}),
    ("history", "czy hałas wentylatorów ostatnio narasta?", {"fan_noise_history"}),
    ("history", "has fan noise been getting worse over time?", {"fan_noise_history"}),
    ("history", "porównaj dzisiejsze zużycie RAM z moją normą", {"ram_compare"}),
    ("history", "is current memory use above my usual baseline?", {"ram_compare"}),
    ("history", "ile pamięci przeciętnie zużywam w ciągu dnia?", {"daily_ram_usage"}),
    ("history", "show my typical daily memory consumption", {"daily_ram_usage"}),
    ("history", "dlaczego ten sam program zachowuje się dziś inaczej?", {"app_behavior_change"}),
    ("history", "why is this app using more resources than usual?", {"app_behavior_change"}),
    ("history", "co zapamiętałeś o sposobie używania przeze mnie komputera?", {"ai_context"}),
    ("history", "what have you learned locally about my normal PC usage?", {"ai_context"}),
    ("history", "przypomnij liczby, które podałeś przed chwilą", {"recall_numbers"}),
    ("history", "what exact values did you mention in the previous answer?", {"recall_numbers"}),
    ("history", "czemu sam czasem wyskakujesz z poradą?", {"explain_proactive"}),
    ("history", "explain why you proactively notified me", {"explain_proactive"}),

    # Gaming, power and battery
    ("gaming", "czy Cyberpunk będzie grywalny na tym zestawie?", {"game_can_run"}),
    ("gaming", "how well should Baldur's Gate 3 run on this hardware?", {"game_can_run"}),
    ("gaming", "sprawdź komputer przed odpaleniem gry", {"game_ready"}),
    ("gaming", "make sure the machine is ready before I start gaming", {"game_ready"}),
    ("gaming", "która z moich gier dociska GPU najmocniej?", {"game_hardware_stress"}),
    ("gaming", "which game has stressed this PC the most?", {"game_hardware_stress"}),
    ("gaming", "po dłuższej grze klatki zaczynają regularnie spadać", {"fps_degradation"}),
    ("gaming", "FPS gets worse after about an hour of playing", {"fps_degradation"}),
    ("gaming", "jak wyglądała ostatnia sesja grania?", {"gaming_session"}),
    ("gaming", "summarize the last time I played a game", {"gaming_session"}),
    ("gaming", "ile RAM przeciętnie zajmują u mnie gry?", {"gaming_ram_usage"}),
    ("gaming", "what is my normal memory footprint while gaming?", {"gaming_ram_usage"}),
    ("gaming", "porównaj czas spędzony w grach i przy pracy", {"gaming_vs_work_time"}),
    ("gaming", "do I spend more computer time working or gaming?", {"gaming_vs_work_time"}),
    ("power", "jaki profil zasilania mam obecnie włączony?", {"power_plan"}),
    ("power", "which Windows power mode is active?", {"power_plan"}),
    ("power", "czy po restarcie komputer pobiera więcej energii?", {"power_after_restart"}),
    ("power", "did power consumption change after rebooting?", {"power_after_restart"}),
    ("power", "bateria znika zdecydowanie szybciej niż zwykle", {"battery_drain"}),
    ("power", "why has the laptop battery started draining so fast?", {"battery_drain"}),
    ("power", "w jakim tempie ubywa teraz procentów baterii?", {"battery_drain_rate"}),
    ("power", "calculate the current battery discharge rate", {"battery_drain_rate"}),
    ("power", "na ile mniej więcej wystarczy jeszcze akumulator?", {"battery_estimate"}),
    ("power", "roughly how much battery time remains?", {"battery_estimate"}),
    ("power", "czy ktoś podkręcał ten procesor albo kartę?", {"overclock_check"}),
    ("power", "do the current clocks suggest an overclock?", {"overclock_check"}),

    # Upgrade, cooling and guided help
    ("upgrade", "co da największy odczuwalny skok po wymianie?", {"upgrade_advice"}),
    ("upgrade", "which single upgrade would improve this PC the most?", {"upgrade_advice"}),
    ("upgrade", "czy ten komputer ma jeszcze sensowną drogę rozbudowy?", {"upgrade_feasibility"}),
    ("upgrade", "is this platform worth upgrading or is it a dead end?", {"upgrade_feasibility"}),
    ("upgrade", "ułóż kolejność zakupów, żebym nie przepalił budżetu", {"upgrade_plan"}),
    ("upgrade", "build an evidence-based upgrade roadmap for this machine", {"upgrade_plan"}),
    ("upgrade", "czy Ryzen 7 5700X zadziała na mojej obecnej płycie?", {"upgrade_compat"}),
    ("upgrade", "mam RTX 3060, czy wymiana na RTX 5070 ma tu sens i będzie zgodna?", {"upgrade_compat"}),
    ("upgrade", "will a Core Ultra 7 270K Plus fit my current platform?", {"upgrade_compat"}),
    ("upgrade", "czy mogę dołożyć DDR4 3600 do obecnych modułów?", {"ram_compat"}),
    ("upgrade", "will a 32 GB DDR5 kit work with what I already have?", {"ram_compat"}),
    ("upgrade", "jaki typ i taktowanie pamięci mogę bezpiecznie dokupić?", {"ram_compat"}),
    ("upgrade", "temperatury są za wysokie, przeprowadź mnie przez chłodzenie", {"cooling_advice"}),
    ("upgrade", "guide me through reducing heat without guessing", {"cooling_advice"}),
    ("upgrade", "od czego zacząć bezpieczne porządki wydajnościowe?", {"optimize_guide", "optimization"}),
    ("upgrade", "walk me through optimization one safe step at a time", {"optimize_guide"}),
    ("upgrade", "sprawdź co można poprawić, ale niczego sam nie wyłączaj", {"optimization"}),
    ("upgrade", "analyze safe optimization opportunities on this PC", {"optimization"}),
    ("upgrade", "zrób mi pełny przegląd i plan dopieszczenia systemu", {"tuneup_guide"}),
    ("upgrade", "I want a guided full-system tune-up", {"tuneup_guide"}),
    ("upgrade", "czy warto opróżnić RAM przed uruchomieniem gry?", {"ram_flush"}),
    ("upgrade", "would trimming working sets actually help right now?", {"ram_flush"}),
    ("upgrade", "czy tryb turbo coś tu realnie poprawi?", {"turbo_boost"}),
    ("upgrade", "what would PC Workman's turbo mode change?", {"turbo_boost"}),
    ("upgrade", "ustaw krzywą wentylatorów na podstawie obecnych danych", {"fan_consult", "fan_apply_ai"}),
    ("upgrade", "help me configure a sensible fan curve", {"fan_consult"}),

    # Conversation, identity, trust and loose language
    ("conversation", "hejka, jesteś tam ze mną?", {"greeting", "small_talk"}),
    ("conversation", "dzień dobry, zaczynamy kolejne sprawdzanie?", {"greeting"}),
    ("conversation", "yo, ready to look at my PC?", {"greeting"}),
    ("conversation", "dzięki, właśnie o taką odpowiedź mi chodziło", {"thanks"}),
    ("conversation", "that cleared things up, thank you", {"thanks"}),
    ("conversation", "jak tam u ciebie, mały mechaniku?", {"small_talk"}),
    ("conversation", "what do you think about how this PC is behaving?", {"small_talk"}),
    ("conversation", "powiedz coś luźno, ale oprzyj to na stanie komputera", {"small_talk"}),
    ("conversation", "zjedź mój komputer, tylko użyj prawdziwych danych", {"fun_roast"}),
    ("conversation", "roast this machine based on its actual condition", {"fun_roast"}),
    ("conversation", "czym dokładnie jesteś i po co siedzisz w programie?", {"about_program"}),
    ("conversation", "explain what PC Workman is in plain language", {"about_program"}),
    ("conversation", "kto cię stworzył i rozwija ten projekt?", {"about_author"}),
    ("conversation", "who is the person behind PC Workman?", {"about_author"}),
    ("conversation", "nie wiem, od czego zacząć, pokaż dostępne możliwości", {"help"}),
    ("conversation", "what kinds of computer questions can I ask you?", {"help"}),
    ("conversation", "gdzie zapisujesz informacje, których uczysz się o moim PC?", {"privacy_data"}),
    ("conversation", "does any of my monitoring data leave this computer?", {"privacy_data"}),
    ("conversation", "czy mój system wygląda obecnie zdrowo?", {"health_check"}),
    ("conversation", "give the machine a quick safety and health check", {"health_check"}),
    ("conversation", "czy jest teraz jakiś poważny powód do niepokoju?", {"system_risk", "health_check"}),
    ("conversation", "is anything currently putting the system at real risk?", {"system_risk"}),

    # Intentionally messy, short and mixed-language inputs
    ("messy", "ej czemu ten komp tak muli dzis", {"why_slow"}),
    ("messy", "temp procka jest okej czy lipa?", {"temperature"}),
    ("messy", "gpu hot czy moge dalej grac", {"temperature", "gpu_temp_why"}),
    ("messy", "ramu prawie ni ma a nic nie wlaczylem", {"ram_why_high"}),
    ("messy", "co mi mieli dysk w tle pls", {"disk_usage_why"}),
    ("messy", "ten proces safe czy jakis syf?", {"process_identity", "virus_check"}),
    ("messy", "moge ubic Discord.exe bez rozpierduchy?", {"process_kill"}),
    ("messy", "boot od tygodnia wolniejszy, why?", {"startup_slowdown"}),
    ("messy", "pulpit kaput, taskbar tez, mysz zyje", {"desktop_problem"}),
    ("messy", "rtx 5070 wejdzie do tego pc czy nie bardzo", {"upgrade_compat"}),
    ("messy", "ddr5 6000 bedzie sie gryzl z tym co mam?", {"ram_compat"}),
    ("messy", "jaki upgrade najpierw zeby bylo czuc roznice", {"upgrade_advice"}),
    ("messy", "po godzinie gry fps robi nura", {"fps_degradation"}),
    ("messy", "ile baterii zostalo tak mniej wiecej", {"battery_estimate"}),
    ("messy", "hej checknij cpu clock na szybko", {"cpu_clock"}),
    ("messy", "show mi co teraz zjada najwiecej", {"top_resource_hog"}),
]


OOD_QUERY_CASES = [
    ("weather", "czy po południu będzie padać w Warszawie?"),
    ("weather", "give me the weekend weather forecast"),
    ("writing", "napisz za mnie wiadomość do rekrutera"),
    ("writing", "rewrite this paragraph so it sounds formal"),
    ("food", "co szybkiego ugotować z makaronu i pomidorów?"),
    ("food", "how long should I bake a sourdough loaf?"),
    ("travel", "znajdź najtańszy lot do Amsterdamu"),
    ("travel", "plan a three-day trip around Prague"),
    ("news", "co ważnego wydarzyło się dziś na świecie?"),
    ("news", "summarize today's political news"),
    ("sports", "jaki był wynik wczorajszego meczu Legii?"),
    ("sports", "who won the Formula 1 race?"),
    ("education", "wytłumacz mi fotosyntezę przed sprawdzianem"),
    ("education", "solve this quadratic equation for me"),
    ("translation", "przetłumacz ten list na język niemiecki"),
    ("translation", "how do I say good morning in Japanese?"),
    ("creative", "napisz smutny wiersz o jesieni"),
    ("creative", "invent a fantasy character with a dragon"),
    ("finance", "czy warto teraz kupić akcje Nvidii?"),
    ("finance", "what mortgage can I afford?"),
    ("medical", "od dwóch dni boli mnie gardło, co brać?"),
    ("medical", "does this rash require a doctor?"),
    ("legal", "napisz mi odwołanie od mandatu"),
    ("legal", "is this rental contract clause legal?"),
    ("shopping", "poleć mi dobry ekspres do kawy"),
    ("shopping", "find a comfortable office chair under 300 dollars"),
    ("general", "dlaczego niebo zmienia kolor o zachodzie?"),
    ("general", "how far away is the moon?"),
    ("calendar", "przypomnij mi jutro o piętnastej o spotkaniu"),
    ("calendar", "book a meeting with Anna next Friday"),
    ("email", "wyślij wiadomość do mojego szefa"),
    ("email", "check whether I received an email from Tom"),
    ("nonsense", "fioletowy banan śpiewa przez teleskop"),
    ("nonsense", "umbrella quantum potato orchestra"),
    ("ambiguous", "zrób to za mnie"),
    ("ambiguous", "dlaczego tak jest?"),
]


# (initial query, initial intent, follow-up, accepted follow-up intents)
CONTEXT_QUERY_CASES = [
    ("pokaż temperaturę GPU", "gpu_temp_why", "a ile ma teraz stopni?", {"gpu_temp_why"}),
    ("jaki mam procesor", "hw_cpu", "a jego temperatura?", {"temperature"}),
    ("pokaż kartę graficzną", "hw_gpu", "is it running hot?", {"gpu_temp_why"}),
    ("co robi Discord.exe", "process_info", "czy mogę go zamknąć?", {"process_kill"}),
    ("tell me about OneDrive.exe", "process_info", "can I stop it safely?", {"process_kill"}),
    ("czym jest SearchHost.exe", "process_identity", "więcej o nim", {"process_deep_dive"}),
    ("identify audiodg.exe", "process_identity", "what does it do?", {"process_deep_dive"}),
    ("chcę kupić RTX 5070", "upgrade_advice", "czy będzie pasować?", {"upgrade_compat"}),
    ("thinking about DDR5 6000", "upgrade_advice", "will that fit?", {"ram_compat"}),
    ("czy temperatury są bezpieczne", "temperature", "sprawdź ponownie", {"temperature"}),
    ("show current power plan", "power_plan", "and now?", {"power_plan"}),
    ("co zmieniło się od wczoraj", "pc_changes", "wróć do tego", {"pc_changes"}),
    ("summarize this session", "session_digest", "continue that topic", {"session_digest"}),
]

